/* Every visible string in the nine step figures: labels, sample data,
 * explanations and the text description of each figure.
 *
 * Rules (release 1 contract): no em dashes, no exclamation marks, "we"
 * never "I", plain English, "AI" only in steps 3 and 7. Sample companies,
 * people and values are illustrative and tagged so. The only real numbers
 * are the cleared ones: 18,000 up to 80,000+ emails a month, 2 in 100,
 * 13 bounces in 2,996 (0.43%), day 0, 3 and 7, within a minute, 21 days of
 * warm-up, 30 emails a day per inbox and 4 inboxes per web address. */

export const COPY = {
  illustrative: 'Illustrative',

  /* ───────────── 1 · Who you want as customers ───────────── */
  s1: {
    name: 'Campaign designer',
    desc:
      'A campaign designer. On the left, a card titled Your ideal customer lists four fields: industry, staffing and executive search firms; company size, 10 to 200 people; where, Pune, Mumbai and Bengaluru; who decides, the founder or head of sales. On the right, five campaign types, each with one goal: new companies, a reason to write, old leads, no-shows and not-nows, and more like your best customers. Choosing a type draws a line to it from the card and shows its goal, who it reaches and an example opening line. All values are illustrative.',
    specLabel: 'Agreed with you',
    specTitle: 'Your ideal customer',
    spec: [
      { k: 'Industry', v: 'Staffing and executive search firms' },
      { k: 'Company size', v: '10 to 200 people' },
      { k: 'Where', v: 'Pune, Mumbai, Bengaluru' },
      { k: 'Who decides', v: 'Founder or head of sales' },
    ],
    listLabel: 'Five campaign types. Pick one',
    goalLabel: 'Its one goal',
    reachLabel: 'Who it reaches',
    openLabel: 'Example opening',
    campaigns: [
      {
        key: 'new',
        name: 'New companies',
        from: 'Never heard of you',
        to: 'a first meeting',
        goal: 'A first meeting with a company that has never heard of you.',
        reach: 'Firms that match your ideal customer and have no history with you.',
        opening: 'You place senior hires for manufacturers across Pune, so this may be worth two minutes of your time.',
      },
      {
        key: 'reason',
        name: 'A reason to write',
        from: 'Something just changed',
        to: 'a meeting while the need is live',
        goal: 'A meeting while the need is still live.',
        reach: 'Firms with a fresh reason to talk: a new hire, funding, a tender or a new office.',
        opening: 'Saw you are opening a Bengaluru office this quarter, which usually means hiring fast.',
      },
      {
        key: 'old',
        name: 'Old leads',
        from: 'Your own past enquiries',
        to: 'restart the conversation',
        goal: 'Restart a conversation that went quiet.',
        reach: 'People who enquired with you before and never went ahead.',
        opening: 'You asked us about this back in March. A few things have changed on our side since then.',
      },
      {
        key: 'rebook',
        name: 'No-shows and not-nows',
        from: 'Missed or put off',
        to: 'rebook',
        goal: 'Get the meeting back in the calendar.',
        reach: 'People who missed a meeting, or asked you to come back later.',
        opening: 'We missed each other on Thursday. Would Tuesday at 11:00 work instead?',
      },
      {
        key: 'like',
        name: 'More like your best customers',
        from: 'Your ten best',
        to: 'more of the same',
        goal: 'More companies like the ten you most like working with.',
        reach: 'Firms that look like your ten best customers, by size, city and what they do.',
        opening: 'We work with a few firms much like yours in Mumbai, and thought this might suit you too.',
      },
    ],
    announce: (name: string, goal: string) => `${name}. Its goal: ${goal}`,
  },

  /* ───────────── 2 · Your own sending setup ───────────── */
  s2: {
    name: 'Sending setup',
    desc:
      'A diagram of the sending setup. Your main web address, yourcompany.com, sits apart inside a dashed boundary labelled never used for outreach. A sending account used only for you fans out to five web addresses built on the same name: getyourcompany.com, yourcompanyhq.com, tryyourcompany.com, meetyourcompany.com and yourcompany.co, each with four inboxes. Every address is signed, verified and protected. You can type your company name to see the addresses change, worked out in your browser with nothing sent. A line chart shows the 21-day warm-up, from 5 to 10 emails a day per inbox up to 20, marked ready at day 21. A slider sizes the setup from 18,000 up to 80,000+ emails a month, at 30 emails a day per inbox and 4 inboxes per web address. Web addresses and sizing are illustrative.',
    nameLabel: 'Type your company name',
    namePlaceholder: 'yourcompany',
    nameHint: 'Worked out in your browser. Nothing is sent.',
    mainSub: 'Your main email',
    mainNote: 'Never used for outreach',
    origin: 'Sending account',
    originSub: 'used only for you',
    colDomainShort: 'Web address',
    colInboxes: 'Inboxes',
    colChecks: 'Checks',
    inboxNames: ['priya', 'arjun', 'neha', 'kabir'],
    checks: [
      { key: 'signed', name: 'Signed', what: 'A signature on every email, proving it really came from you.' },
      { key: 'verified', name: 'Verified', what: 'A public list of which servers may send email for you.' },
      { key: 'protected', name: 'Protected', what: 'An instruction telling inboxes what to do with fakes.' },
    ],
    checksLead: 'Every address is',
    checksHint: 'Point at or tap a check to see what it means.',
    more: (n: number) => `Plus ${n} more web addresses like these, at the volume set below.`,
    moreBase: 'At 18,000 a month, these five are enough.',
    warmTitle: 'Warm-up, 21 days',
    warmAxis: 'Emails a day, per inbox',
    warmStart: 'Day 1',
    warmEnd: 'Day 21',
    warmReady: 'Ready',
    sizeTitle: 'Illustrative sizing',
    sizeLabel: 'Emails a month',
    sizeRule: '30 emails a day per inbox. 4 inboxes per web address.',
    sizeOut: (inboxes: number, domains: number) => `About ${inboxes} inboxes across ${domains} web addresses`,
    grid: (inboxes: number) => `${inboxes} inboxes, drawn in groups of four`,
  },

  /* ───────────── 3 · AI checks every company first ───────────── */
  s3: {
    name: 'Company check',
    desc:
      'A flow diagram. Four sources, maps, business directories, web search and professional networks, flow into one longlist of companies. An AI agent then reads each company’s website before anyone is looked up. Two browser tabs switch between two illustrative companies. Altair Executive Search, a leadership hiring firm for manufacturers, is marked Fits your customer profile, with the lines that decided it highlighted. Linden Home Studio, a residential interior studio, is marked Not a fit, skipped, because it designs homes, even though its blog mentions staffing once.',
    sources: [
      { key: 'maps', label: 'Maps', icon: 'pin' },
      { key: 'dirs', label: 'Business directories', icon: 'list' },
      { key: 'web', label: 'Web search', icon: 'search' },
      { key: 'nets', label: 'Professional networks', icon: 'users' },
    ],
    longlist: 'One longlist',
    longlistSub: 'Every company found, from all four',
    reads: 'An AI agent reads each website',
    note: 'Checked before anyone is looked up.',
    reading: 'Reading',
    decoyTag: 'One mention, not the business',
    pickLabel: 'Sample company',
    nav: ['About', 'Services', 'Clients', 'Contact'],
    companies: [
      {
        key: 'fit',
        name: 'Altair Executive Search',
        short: 'Altair',
        url: 'altairsearch.in',
        tagline: 'Leadership hiring for manufacturing firms',
        lines: [
          'We find plant heads and CXOs for manufacturers.',
          'Our clients make auto parts and machinery.',
          'Founded in 2011, in Pune and Mumbai.',
        ],
        evidence: [0, 1],
        decoy: -1,
        verdict: 'Fits your customer profile',
        why: 'Hires leaders for manufacturers, which is who you sell to.',
        next: 'Next: find who decides',
        announce: 'Altair Executive Search: fits your customer profile.',
      },
      {
        key: 'skip',
        name: 'Linden Home Studio',
        short: 'Linden',
        url: 'lindenhome.in',
        tagline: 'Residential interiors for apartments and villas',
        lines: [
          'We design homes, from one room to a full villa.',
          'Most of our clients are families in Pune.',
          'From our blog: how we staffed our first site team.',
        ],
        evidence: [0, 1],
        decoy: 2,
        verdict: 'Not a fit · skipped',
        why: 'Designs homes for families. The one mention of staffing is about its own site team.',
        next: 'Nobody looked up',
        announce: 'Linden Home Studio: not a fit, skipped.',
      },
    ],
    pause: 'Pause the flow',
    play: 'Play the flow',
  },

  /* ───────────── 4 · A reason to write ───────────── */
  s4: {
    name: 'Reasons to write',
    desc:
      'A 30-day timeline of reasons to write, from 30 days ago to today, with five markers: a new leader in their first 90 days, a seed round, a tender published, a new office in Hyderabad, and a Head of Sales being hired. Choosing a marker rewrites the first line of an email preview for that company, with a label saying why now. The rest of the email stays the same. All companies and people are illustrative.',
    watch: 'Watchlist, last 30 days',
    axisStart: '30 days ago',
    axisEnd: 'Today',
    pickLabel: 'Reasons to write',
    ago: (d: number) => (d === 1 ? '1 day ago' : `${d} days ago`),
    whyNow: 'Why now',
    from: 'From',
    fromValue: 'You',
    to: 'To',
    subject: 'Subject',
    newMsg: 'New email',
    rest: 'The rest of the email',
    signals: [
      {
        key: 'leader',
        label: 'New leader, first 90 days',
        short: 'New leader',
        ago: 28,
        to: 'Asha Menon, Orbit Workforce',
        subject: 'Your first 90 days',
        line: 'Congratulations on the new role. The first 90 days are usually when plans get set.',
      },
      {
        key: 'seed',
        label: 'Seed round',
        short: 'Seed round',
        ago: 21,
        to: 'Neha Iyer, Brightpath Robotics',
        subject: 'After the seed round',
        line: 'Congratulations on the seed round. Hiring is usually the next thing on the list.',
      },
      {
        key: 'tender',
        label: 'Tender published',
        short: 'Tender published',
        ago: 15,
        to: 'Arjun Mehta, Deccan Facilities',
        subject: 'The Chakan tender',
        line: 'Saw the housekeeping tender you published for the Chakan plant.',
      },
      {
        key: 'office',
        label: 'New office in Hyderabad',
        short: 'New office',
        ago: 9,
        to: 'Kabir Shah, Northbay Systems',
        subject: 'The Hyderabad office',
        line: 'Congratulations on opening the Hyderabad office.',
      },
      {
        key: 'hire',
        label: 'Hiring a Head of Sales',
        short: 'Head of Sales hire',
        ago: 2,
        to: 'Ritika Rao, Altair Executive Search',
        subject: 'Your Head of Sales search',
        line: "Saw you're hiring a Head of Sales for the Pune team.",
      },
    ],
    announce: (label: string, line: string) => `${label}. First line: ${line}`,
  },

  /* ───────────── 5 · Every address checked ───────────── */
  s5: {
    name: 'Address checks',
    desc:
      'A flow of one illustrative list of 1,000 addresses through four checks. The mail server exists: 940 pass. A bulk check: 900. A direct check with their server: 880. A check on addresses that accept anything: 842 verified, with 38 risky set aside as their own group. A final check that the person still works there leaves 830 ready. Below it, a bounce gate: a slider sets the list’s estimated bounce rate from 0 to 5 percent against a limit line at 2 in 100. Under the line the list is loaded; over it, the list is held and not sent. Beside the gate, our own sending: 13 bounces in 2,996 emails, 0.43 percent, and nobody unsubscribed.',
    flowTitle: 'One list, four checks',
    start: 'Addresses found',
    stages: [
      { label: 'The mail server exists', n: 940 },
      { label: 'Bulk check', n: 900 },
      { label: 'A direct check with their server', n: 880 },
      { label: 'A check on addresses that accept anything', n: 842 },
    ],
    startN: 1000,
    risky: 38,
    riskyLabel: 'risky, set aside as their own group',
    final: 'Still works there',
    finalN: 830,
    finalGone: 'left the company, removed',
    removed: 'removed',
    verified: 'verified',
    ready: 'ready',
    gateTitle: 'The bounce gate',
    sliderLabel: 'Estimated bounce rate, 0% to 5%',
    sliderFor: (n: string) => `Estimated bounce rate for this list of ${n}`,
    limit: '2 in 100',
    ours: 'Our sending',
    loaded: 'Loaded',
    held: 'Held, not sent',
    loadedWhy: 'Fewer than 2 in 100 would bounce, so the list goes out.',
    heldWhy: 'More than 2 in 100 would bounce, so the list is not sent.',
    proofLabel: 'Our own sending, since August',
    pct: (n: number) => `${n.toFixed(1)}%`,
    announce: (status: string, pct: string) => `${pct}: ${status}`,
  },

  /* ───────────── 6 · Three short emails ───────────── */
  s6: {
    name: 'The week and the test',
    desc:
      'A one-week line with three emails: day 0, day 3 and day 7. The third brings a new angle. After day 7 the line stops, with no fourth email, or branches to LinkedIn for the people worth it. Below, a one-change test: version A and version B of an email are identical except for one line, the ask at the end, which is highlighted. Under 200 sends, a result is only a hint. All emails and send counts are illustrative.',
    week: 'One week, three emails',
    days: [
      { day: 'Day 0', n: 'Email 1', subject: 'Your Head of Sales search', first: "Saw you're hiring a Head of Sales for the Pune team." },
      { day: 'Day 3', n: 'Email 2', subject: 'Re: Your Head of Sales search', first: 'The one question most founders ask us, answered in two lines.' },
      { day: 'Day 7', n: 'Email 3', subject: 'A different idea for the search', first: 'Most new sales heads spend month one finding leads. We could take that part.', angle: 'A new angle' },
    ],
    after: 'After day 7',
    stop: 'Stop',
    stopSub: 'No fourth email',
    li: 'LinkedIn',
    liSub: 'For the ones worth it',
    liNote: 'A short connection note',
    abTitle: 'One-change test',
    toggle: 'Show version',
    versions: [
      { key: 'a', label: 'Version A' },
      { key: 'b', label: 'Version B' },
    ],
    subjectK: 'Subject',
    emailSubject: 'Your Head of Sales search',
    emailFirst: "Saw you're hiring a Head of Sales for the Pune team.",
    same: 'Identical in both',
    askA: 'Worth a 15-minute call next week?',
    askB: 'Should we send a two-line summary first?',
    change: 'The one change',
    rule: 'Under 200 sends, a result is only a hint.',
    sendsLabel: 'Sends so far',
    sends: [
      { key: 'a', label: 'A', n: 140 },
      { key: 'b', label: 'B', n: 136 },
    ],
    hint: 'Still a hint',
    of: 'of 200',
    announce: (label: string, ask: string) => `${label}. The ask: ${ask}`,
  },

  /* ───────────── 7 · Sorted in under a minute ───────────── */
  s7: {
    name: 'Reply sorting',
    desc:
      'A reply sorting board. A sample reply arrives, an AI agent reads it while a timer runs and stops under a minute, and the reply moves into one of seven lanes: interested, not sure, a question, a referral, not now, remove me, or automatic reply. Four illustrative replies can be chosen: a request for more, a question, a not this quarter, and an out-of-office. A mode setting, book them straight in, ask your questions first, or hand to your team, changes the drafted answer. Every draft is marked a person approves this first, and quotes and contracts always go to your team.',
    pickLabel: 'Pick a sample reply',
    lanesLabel: 'Sorted into',
    timerLabel: 'Read and sorted in',
    lanes: ['Interested', 'Not sure', 'A question', 'A referral', 'Not now', 'Remove me', 'Automatic reply'],
    replies: [
      { key: 'int', from: 'Ritika Rao', company: 'Altair Executive Search', text: 'This looks relevant. Can you share more?', pick: 'Can you share more?', lane: 0, secs: 38 },
      { key: 'q', from: 'Arjun Mehta', company: 'Northbay Systems', text: 'Does this work for a firm with 15 people?', pick: 'Does this work for 15 people?', lane: 2, secs: 41 },
      { key: 'later', from: 'Dev Malhotra', company: 'Tidewater HR', text: 'Not this quarter. Try us again in January.', pick: 'Not this quarter', lane: 4, secs: 29 },
      { key: 'auto', from: 'Asha Menon', company: 'Orbit Workforce', text: 'Out of the office until Monday, with limited email.', pick: 'Out of the office', lane: 6, secs: 12 },
    ],
    modeLabel: 'Your way',
    modes: [
      { key: 'book', label: 'Book them straight in' },
      { key: 'ask', label: 'Ask your questions first' },
      { key: 'hand', label: 'Hand to your team' },
    ],
    draftLabel: 'Drafted answer',
    approve: 'A person approves this first',
    always: 'Quotes and contracts always go to your team.',
    drafts: {
      int: {
        book: 'Thanks, Ritika. The quickest way is a 20-minute call. Thursday at 11:00 or Friday at 15:00 both work. Shall we hold one?',
        ask: 'Thanks, Ritika. Two quick questions first, so the call is useful: how many roles are you hiring for this quarter, and who else decides?',
        hand: 'Thanks, Ritika. We have passed this to Karan on our team, who will write to you today with the details.',
      },
      q: {
        book: 'Yes, it works for a team that size. Would a 20-minute call on Thursday at 11:00 help?',
        ask: 'Yes, it does. To answer properly: how do new clients find you today, and who handles sales?',
        hand: 'Good question. We have passed it to Karan on our team, who knows this best and will reply today.',
      },
      later: {
        all: 'Understood, Dev. We will write again in the second week of January.',
        note: 'A not-now gets a reason and a date, whatever the mode.',
      },
      auto: {
        all: 'No answer sent.',
        note: 'An automatic reply is not counted as a reply.',
      },
    },
    announce: (lane: string, secs: string) => `Sorted as ${lane} in ${secs}.`,
  },

  /* ───────────── 8 · Email, LinkedIn, call, WhatsApp ───────────── */
  s8: {
    name: 'One conversation, four channels',
    desc:
      'Four swimlanes: email, LinkedIn, call, and WhatsApp once they agree. One illustrative conversation hops across them: an email sent on Monday at 10:02, a reply at 12:40, a LinkedIn connection on Tuesday, a 14-minute call on Wednesday at 16:00, and the time confirmed on WhatsApp at 16:20. Below, a CRM table of four illustrative companies whose status cells update themselves from Emailed to Replied to Meeting booked, stamped updated automatically. Pointing at or focusing a row shows what changed it and when. A research brief card is ready before the meeting: who they are, why we wrote, and what to ask.',
    lanes: [
      { key: 'email', label: 'Email', icon: 'mail' },
      { key: 'li', label: 'LinkedIn', icon: 'users' },
      { key: 'call', label: 'Call', icon: 'phone' },
      { key: 'wa', label: 'WhatsApp', icon: 'chat', note: 'once they agree' },
    ],
    path: [
      { lane: 0, t: 'Mon 10:02', text: 'Email 1 sent' },
      { lane: 0, t: 'Mon 12:40', text: 'They reply: send details' },
      { lane: 1, t: 'Tue 09:15', text: 'Connected on LinkedIn' },
      { lane: 2, t: 'Wed 16:00', text: 'Call, 14 min' },
      { lane: 3, t: 'Wed 16:20', text: 'Time confirmed' },
    ],
    crmTitle: 'Your CRM',
    stamp: 'Updated automatically',
    cols: ['Company', 'Contact', 'Status'],
    statuses: ['Not contacted', 'Emailed', 'Replied', 'Meeting booked'],
    rows: [
      {
        company: 'Altair Executive Search',
        contact: 'Ritika Rao',
        steps: [
          { s: 1, why: 'Email 1 sent', when: 'Mon 10:02' },
          { s: 2, why: 'Reply received by email', when: 'Mon 12:40' },
          { s: 3, why: 'Thursday 11:00 agreed on the call', when: 'Wed 16:05' },
        ],
      },
      {
        company: 'Northbay Systems',
        contact: 'Arjun Mehta',
        steps: [
          { s: 1, why: 'Email 1 sent', when: 'Mon 10:14' },
          { s: 2, why: 'Replied on LinkedIn', when: 'Tue 11:30' },
        ],
      },
      {
        company: 'Tidewater HR',
        contact: 'Dev Malhotra',
        steps: [{ s: 1, why: 'Email 1 sent', when: 'Mon 10:26' }],
      },
      {
        company: 'Orbit Workforce',
        contact: 'Asha Menon',
        steps: [
          { s: 1, why: 'Email 1 sent', when: 'Tue 10:02' },
          { s: 2, why: 'Reply received by email', when: 'Wed 09:48' },
        ],
      },
    ],
    rowHint: 'Point at or focus a row to see what changed it.',
    rowWhy: (company: string, status: string, why: string, when: string) => `${company}: ${status}. ${why}, ${when}.`,
    brief: {
      title: 'Brief ready before the meeting',
      for: 'Ritika Rao · Thu 11:00',
      items: [
        { k: 'Who they are', v: 'Founder of Altair Executive Search. Leadership hiring for manufacturers in Pune and Mumbai.' },
        { k: 'Why we wrote', v: 'They are hiring a Head of Sales for the Pune team.' },
        { k: 'What to ask', v: 'How many roles this quarter, and who else decides.' },
      ],
    },
  },

  /* ───────────── 9 · Booked, confirmed, reminded ───────────── */
  s9: {
    name: 'Meeting lifecycle',
    desc:
      'A state diagram of a meeting. The main path runs booked, confirmed, reminded, held. If they do not show: no-show, followed up, rebooked, and back to booked. If they say not now: the reason is noted with a wake date, and the follow-up goes out by itself on that date. You can pick a not-now reason, budget opens in January, after our hiring freeze, or call me next quarter, and the wake date is worked out from today and marked on a small calendar.',
    main: [
      { key: 'booked', label: 'Booked', sub: 'About 3 days, where possible' },
      { key: 'confirmed', label: 'Confirmed', sub: 'They say yes' },
      { key: 'reminded', label: 'Reminded', sub: 'Before it starts' },
      { key: 'held', label: 'Held', sub: 'You take the call' },
    ],
    noshow: [
      { key: 'noshow', label: 'No-show', sub: 'They miss it' },
      { key: 'followed', label: 'Followed up', sub: 'A short note' },
      { key: 'rebooked', label: 'Rebooked', sub: 'Back to booked' },
    ],
    notnow: [
      { key: 'notnow', label: 'Not now', sub: 'They say later' },
      { key: 'wake', label: 'Reason and wake date', sub: '' },
      { key: 'auto', label: 'Follow-up goes out', sub: 'By itself' },
    ],
    tracks: ['Main path', 'If they miss it', 'If they say not now'],
    reply: 'A reply',
    reasonsLabel: 'Pick a not-now reason',
    reasons: [
      { key: 'budget', label: 'Budget opens in January', rule: 'First Monday of January' },
      { key: 'freeze', label: 'After our hiring freeze', rule: '60 days from today, on a weekday' },
      { key: 'quarter', label: 'Call me next quarter', rule: 'Second week of next quarter' },
    ],
    wakeLabel: 'Wake date',
    today: 'Today',
    wakeOut: (date: string) => `The follow-up goes out by itself on ${date}.`,
    noDate: 'The wake date is worked out from today’s date, in your browser.',
    weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    wd: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    monthsLong: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    announce: (reason: string, date: string) => `${reason}. Wake date ${date}.`,
  },
} as const;
